twig:
    file_name_pattern: '*.twig'
    globals:
        wedding_date_iso: '%app.wedding_date_iso%'
        wedding_date_label: '%app.wedding_date_label%'

when@test:
    twig:
        strict_variables: true
